version: 2.1

working_directory: /tmp

orbs:
  aws-cli: circleci/aws-cli@4.1.2

jobs:
  checkout_code:
    docker: 
      - image: cimg/node:21.2.0
    steps:
      - checkout

  install:
    docker: 
      - image: cimg/node:21.2.0
    steps:
      - checkout
#      - run:
#          name: "Yarn install"
#          command: yarn
#      - run:
#          name: "Build application"
#          command: yarn build
      - run:
          name: "LS"
          command: ls && ls -la && cd /tmp && ls && ls -la

      - run:
            name: "Deploy app"
            command: aws s3 sync dist/ s3://my-test-bucket-7878 --delete

  build:
    docker:
      - image: cimg/node:21.2.0
    steps:
      - checkout
      - restore_cache:
            key: v1-deps-{{ checksum "yarn-lock" }}
      - run:
          name: "Build application"
          command: yarn build
      - run:
          name: "Deploy app"
          command: echo "Deploy"
      - save_cache:
            key: v1-deps-{{ checksum "yarn-lock" }}
            paths:
              - node_modules

  deploy:
    docker:
      - image: cimg/node:21.2.0
    steps:
      - checkout
      - run:
          name: "Deploy app"
          command: echo "Deploy"

workflows:
  build_and_deploy:
    jobs:
      - checkout_code
      - install:
          requires:
            - checkout_code
#      - build:
#          requires:
#            - install
#      - deploy:
#          requires:
#            - build

# jobs:
#   say-hello:
#     docker:
#       - image: cimg/base:stable
#     steps:
#       - checkout
#       - run: echo "Hello"
#   say-hi:
#     docker:
#       - image: cimg/base:stable
#     steps:
#       - checkout
#       - run:
#           name: "Echo hi"
#           command: echo "Hi"

# workflows:
#   hello_and_hi:
#     jobs:
#       - say-hello
#       - say-hi
         