version: 2.1


jobs:
  checkout_code:
    working_directory: ~/repo
    docker:
      - image: cimg/node:21.2.0
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
      - run:
            name: "mkdir"
            command: touch myFile.txt
      - persist_to_workspace:
            root: ~/
            paths:
              - repo
      - run:
          name: "LS"
          command: ls -d $PWD/*


  install:
    working_directory: ~/repo
    docker:
      - image: cimg/node:21.2.0
    steps:
      - attach_workspace:
            at: ~/repo
      - checkout
      - run:
          name: "Yarn install"
          command: yarn
#      - run:
#          name: "Build application"
#          command: yarn build
      - persist_to_workspace:
          root: ~/
          paths:
            - repo
      - run:
          name: "LS"
          command: ls -d $PWD/*

  build:
    docker:
      - image: cimg/node:21.2.0
    steps:
      - checkout
      - restore_cache:
            key: v1-deps-{{ checksum "yarn-lock" }}
      - run:
          name: "Build application"
          command: yarn build
      - run:
          name: "Deploy app"
          command: echo "Deploy"
      - save_cache:
            key: v1-deps-{{ checksum "yarn-lock" }}
            paths:
              - node_modules

  deploy:
    working_directory: ~/repo
    docker:
      - image: cimg/aws:2023.09
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: ls -d $PWD/*
      - run:
          name: "Deploy app"
          command: aws s3 sync ./dist/ s3://my-test-bucket-7878 --delete

workflows:
  build_and_deploy:
    jobs:
#      - checkout_code
      - install
#          requires:
#            - checkout_code
#      - build:
#          requires:
#            - install
      - deploy:
          requires:
            - install

# jobs:
#   say-hello:
#     docker:
#       - image: cimg/base:stable
#     steps:
#       - checkout
#       - run: echo "Hello"
#   say-hi:
#     docker:
#       - image: cimg/base:stable
#     steps:
#       - checkout
#       - run:
#           name: "Echo hi"
#           command: echo "Hi"

# workflows:
#   hello_and_hi:
#     jobs:
#       - say-hello
#       - say-hi
         