version: 2.1

parameters:
  run_development_workflow:
    default: true
    type: boolean


orbs:
  node: circleci/node@4.1
  aws-cli: circleci/aws-cli@2.0.3

references:
  node_defaults: &node_defaults
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.12.1



jobs:
  checkout_code:
    <<: *node_defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  install:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v8-yarn-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v8-yarn-deps-{{ .Branch }}-
            - v8-yarn-deps-
      - run: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          key: v8-yarn-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/
          paths:
            - repo

  verify_locales:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Verify locales
          command: |
            yarn extract
            if [[ `git diff --exit-code` ]]; then echo "Locales not extracted. Please extract and commit locale files by using 'yarn extract' command" && exit 1; fi

  lint:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn lint

  type_check:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn type-check

workflows:
  development:
    when: << pipeline.parameters.run_development_workflow >>
    jobs:
      - checkout_code
      - install:
          requires:
            - checkout_code
      - verify_locales:
          requires:
            - install
      - lint:
          requires:
            - install
      - type_check:
          requires:
            - install
